- hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - ./vars.yml
  tasks:
    - name: including update-config
      include_role:
        name: homeassistant
        tasks_from: update-config