# reload core
- name: update config_files
  template: dest=/home/homeassistant/.homeassistant/{{ item }} src={{ item }} owner=homeassistant group=homeassistant
  with_items:
    - configuration.yaml
    - customize.yml
    - script.yml
    - secrets.yaml
    - zwave.yml

#copy config folder
- name: copy config folder
  copy: src=config/ dest=/home/homeassistant/.homeassistant/ force=yes owner=homeassistant group=homeassistant

- name: restart homeassistant (EL7)
  systemd: name=homeassistant.service state=restarted daemon_reload=yes
  when:  
    - ansible_os_family  == "RedHat"
    - ansible_distribution_major_version  == "7"

- name: restart homeassistant (Hassbian)
  systemd: name=home-assistant@homeassistant.service state=restarted daemon_reload=yes
  when:  
    - ansible_hostname == "hassbian"

# - debug:
#     msg: "{{ configuration_yml }}"