- name: include centos7
  include: update-centos7.yml
  when:  
  - ansible_os_family == "RedHat"
  - ansible_distribution_major_version  == "7"

- name: include hassbian
  include: update-hassbian.yml
  when:  
  - ansible_hostname == "hassbian"

- name: include hassbian-optionals
  include: update-hassbian-optionals.yml
  when:  
  - ansible_hostname == "hassbian"